create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  price numeric(10,2) not null check (price >= 0),
  photo_url text not null,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "products_select_all" on public.products;
drop policy if exists "products_insert_all" on public.products;
drop policy if exists "products_update_all" on public.products;
drop policy if exists "products_delete_all" on public.products;

create policy "products_select_all"
on public.products
for select
to anon, authenticated
using (true);

create policy "products_insert_all"
on public.products
for insert
to anon, authenticated
with check (true);

create policy "products_update_all"
on public.products
for update
to anon, authenticated
using (true)
with check (true);

create policy "products_delete_all"
on public.products
for delete
to anon, authenticated
using (true);

insert into public.products (title, description, price, photo_url, featured)
values
  ('Aurora Headphones', 'Wireless over-ear headphones with active noise cancellation.', 129.99, 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=80', true),
  ('Nimbus Smart Watch', 'Fitness and health tracking smart watch with AMOLED display.', 199.00, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80', true),
  ('Vertex Backpack', 'Water-resistant urban backpack with laptop compartment.', 74.50, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80', false),
  ('Lumen Desk Lamp', 'Dimmable LED desk lamp with touch controls.', 39.99, 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80', false),
  ('Pulse Bluetooth Speaker', 'Portable speaker with deep bass and 12-hour battery.', 59.00, 'https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=1200&q=80', true),
  ('Terra Coffee Grinder', 'Stainless steel burr grinder with adjustable settings.', 89.90, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80', false),
  ('Echo Mechanical Keyboard', 'Hot-swappable RGB mechanical keyboard.', 109.00, 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80', true),
  ('Orbit Wireless Mouse', 'Ergonomic wireless mouse with silent clicks.', 34.99, 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80', false),
  ('Nova 4K Monitor', '27-inch UHD monitor with HDR support.', 329.00, 'https://images.unsplash.com/photo-1527443224154-c4d10ad2b600?auto=format&fit=crop&w=1200&q=80', true),
  ('Drift Office Chair', 'Breathable mesh chair with lumbar support.', 249.00, 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=1200&q=80', false),
  ('Breeze Air Purifier', 'Compact HEPA air purifier for small rooms.', 119.00, 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', false),
  ('Atlas Water Bottle', 'Insulated stainless steel bottle, 750ml.', 24.99, 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=80', false),
  ('Summit Running Shoes', 'Lightweight running shoes with cushioned sole.', 94.95, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80', true),
  ('Vivid Hoodie', 'Soft cotton blend hoodie with relaxed fit.', 49.00, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80', false),
  ('Crest Yoga Mat', 'Non-slip yoga mat with alignment markings.', 31.50, 'https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?auto=format&fit=crop&w=1200&q=80', false),
  ('Glide Skateboard', 'Maple deck skateboard for street riding.', 79.00, 'https://images.unsplash.com/photo-1547447134-cd3f5c716030?auto=format&fit=crop&w=1200&q=80', false),
  ('Horizon Sunglasses', 'Polarized sunglasses with UV400 protection.', 55.00, 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=80', false),
  ('Craft Chef Knife', '8-inch forged chef knife with ergonomic handle.', 69.00, 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=1200&q=80', false),
  ('Mosaic Dinner Set', '16-piece ceramic dinnerware set.', 89.00, 'https://images.unsplash.com/photo-1612196808214-b7e239e5f0fd?auto=format&fit=crop&w=1200&q=80', false),
  ('Harbor Throw Blanket', 'Cozy woven throw blanket for sofa or bed.', 42.00, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80', false);
